### ISSUE TITLE
Status of code

### ISSUE THREAD

**Issue by mydreamdoctor** [ownprox/ArkServerApi#4]
Firstly, thank you so much for the awesome work.

I'm having some issues compiling many of these plugins, and I'm wondering if perhaps they might no longer be compatible with the newer versions of the API.

I noticed that the plugins that do compile are the ones that have been recently updated. For example, I have no problems compiling PingLimiter.

Any feedback you might be able to provide on what I'm doing wrong would be much appreciated.

Many thanks,

**Comment by Michidu** [comment]
Yes, some of them require a minor changes. What plugins are you trying?

**Comment by mydreamdoctor** [comment]
I've been looking a several of them, primarily to help me understand the API itself.

Particularly the Player List plugin. It seems like a good simple example to get started on.

Thanks for your help.

**Comment by Michidu** [comment]
This plugin compiles fine, what errors are you getting?
